/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pac_form;

import config.Koneksi;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pac_class.PetugasCRUD;
import javax.swing.table.DefaultTableModel;

public class Petugas extends javax.swing.JFrame {
//deklarasi Class LoginCRUD dengan mysql    

    public PetugasCRUD pet = new PetugasCRUD();
//deklarasi class Koneksi
    public Koneksi con = new Koneksi();
//private DefaultTableModel model;
    public DefaultTableModel petugastable;

    public void kosong() {
        PetugasCRUD petid = new PetugasCRUD();
        try {
            TextField_id.setText(petid.getNewId());
            TextField_id.setEditable(false);
        } catch (SQLException ex) {
            Logger.getLogger(Petugas.class.getName()).log(Level.SEVERE, null, ex);
        }
        TextField_id.setEditable(false);

        TextField_nama.setText(null);
        TextArea_alamat.setText(null);
        TextField_password.setText(null);
        TextField_username.setText(null);
        ComboBox_hakakses.setSelectedIndex(0);
        Button_Create.setVisible(true);
        Button_Delete.setVisible(false);
        Button_Update.setVisible(false);

    }

    public Petugas() {

        initComponents();

        jTable_petugas.setModel(pet.viewData());
        pet.viewData();

        buttonGroup1.add(RadioButton_l);
        buttonGroup1.add(RadioButton_p);
        RadioButton_l.setSelected(true);

        kosong();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextField_id = new javax.swing.JTextField();
        alamat = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        hak = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jenis = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        TextField_password = new javax.swing.JTextField();
        TextField_username = new javax.swing.JTextField();
        TextField_nama = new javax.swing.JTextField();
        ComboBox_hakakses = new javax.swing.JComboBox<>();
        RadioButton_p = new javax.swing.JRadioButton();
        RadioButton_l = new javax.swing.JRadioButton();
        nama = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_alamat = new javax.swing.JTextArea();
        Button_Create = new javax.swing.JButton();
        Button_Update = new javax.swing.JButton();
        Button_Delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_petugas = new javax.swing.JTable();
        Button_new = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(46, 68, 92));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 252, 251));
        jLabel1.setText("PETUGAS");

        TextField_id.setBackground(new java.awt.Color(242, 241, 239));

        alamat.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        alamat.setForeground(new java.awt.Color(251, 249, 249));
        alamat.setText("Alamat");

        id.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(251, 249, 249));
        id.setText("ID");

        hak.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        hak.setForeground(new java.awt.Color(251, 249, 249));
        hak.setText("Hak Acess");

        password.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(251, 249, 249));
        password.setText("Password");

        jenis.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jenis.setForeground(new java.awt.Color(251, 249, 249));
        jenis.setText("Jenis Kelamin");

        username.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(251, 249, 249));
        username.setText("Username");

        TextField_password.setBackground(new java.awt.Color(242, 241, 239));

        TextField_username.setBackground(new java.awt.Color(242, 241, 239));

        TextField_nama.setBackground(new java.awt.Color(242, 241, 239));

        ComboBox_hakakses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih hak akses", "Admin", "Petugas", " " }));
        ComboBox_hakakses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_hakaksesActionPerformed(evt);
            }
        });

        RadioButton_p.setBackground(new java.awt.Color(41, 26, 26));
        RadioButton_p.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        RadioButton_p.setForeground(new java.awt.Color(242, 241, 239));
        RadioButton_p.setText("Perempuan");

        RadioButton_l.setBackground(new java.awt.Color(52, 35, 35));
        RadioButton_l.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        RadioButton_l.setForeground(new java.awt.Color(242, 241, 239));
        RadioButton_l.setText("Laki-Laki");

        nama.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        nama.setForeground(new java.awt.Color(251, 249, 249));
        nama.setText("Nama");

        TextArea_alamat.setColumns(20);
        TextArea_alamat.setRows(5);
        jScrollPane1.setViewportView(TextArea_alamat);

        Button_Create.setBackground(new java.awt.Color(242, 38, 19));
        Button_Create.setForeground(new java.awt.Color(6, 6, 6));
        Button_Create.setText("CREATE");
        Button_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CreateActionPerformed(evt);
            }
        });

        Button_Update.setBackground(new java.awt.Color(247, 202, 24));
        Button_Update.setText("UPDATE");
        Button_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_UpdateActionPerformed(evt);
            }
        });

        Button_Delete.setBackground(new java.awt.Color(0, 230, 64));
        Button_Delete.setForeground(new java.awt.Color(4, 20, 16));
        Button_Delete.setText("DELETE");
        Button_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DeleteActionPerformed(evt);
            }
        });

        jTable_petugas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));
        jTable_petugas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable_petugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_petugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_petugasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_petugas);

        Button_new.setBackground(new java.awt.Color(0, 230, 64));
        Button_new.setText("REFRESH");
        Button_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_newActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(242, 38, 19));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id)
                            .addComponent(username)
                            .addComponent(jenis)
                            .addComponent(password)
                            .addComponent(hak)
                            .addComponent(nama)
                            .addComponent(alamat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ComboBox_hakakses, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextField_password, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_username, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(RadioButton_l)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(RadioButton_p))
                            .addComponent(TextField_nama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_id, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Button_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(276, 276, 276))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Button_new, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_new))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(TextField_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nama)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jenis)
                            .addComponent(RadioButton_p)
                            .addComponent(RadioButton_l))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(username)
                            .addComponent(TextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password)
                            .addComponent(TextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hak)
                            .addComponent(ComboBox_hakakses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(alamat)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Button_Update, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_Delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_Create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(999, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBox_hakaksesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_hakaksesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_hakaksesActionPerformed

    private void Button_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CreateActionPerformed
        String gender = null;
        if (RadioButton_l.isSelected() == true) {
            gender = "laki-laki";
        } else {
            gender = "perempuan";
        }

        try {
//            pet.insertPetugas(TextField_id.getText(), TextField_nama.getText(), gender, TextField_username.getText(), TextField_password.getText(), ComboBox_hakakses.getSelectedItem().toString(), TextArea_alamat.getText());
//       JOptionPane.showMessageDialog(rootPane, "Data berhasil disimpan");

            if (TextField_id.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "ID Tidak Boleh Kososng");
            } else if (TextField_nama.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Nama Tidak Boleh Kosong");
            } else if (TextField_username.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "username tidak boleh kosong");
            } else if (TextField_password.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "password tidak boleh kosong");
            } else if (ComboBox_hakakses.getSelectedItem().toString().equals("")) {
                JOptionPane.showMessageDialog(null, "isi combocox");
            } else if (TextArea_alamat.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "isikan alamat dengan benar");
            } else {
                pet.insertPetugas(TextField_id.getText(), TextField_nama.getText(), gender, TextField_username.getText(), TextField_password.getText(), ComboBox_hakakses.getSelectedItem().toString(), TextArea_alamat.getText());
                JOptionPane.showMessageDialog(rootPane, "Data berhasil disimpan");
                jTable_petugas.setModel(pet.viewData());
            }
//       jTable_petugas.setModel(pet.viewData());
//       kosong();
        } catch (SQLException ex) {

            kosong();
            JOptionPane.showMessageDialog(rootPane, "GAGAL");
            Logger.getLogger(Petugas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button_CreateActionPerformed

    private void Button_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_UpdateActionPerformed

        String gender = null;
        if (RadioButton_l.isSelected() == true) {
            gender = "laki-laki";
        } else {
            gender = "perempuan";
        }

        try {
            pet.UpdatePetugas(TextField_nama.getText(),
                    gender,
                    TextField_username.getText(),
                    TextField_password.getText(),
                    ComboBox_hakakses.getSelectedItem().toString(),
                    TextArea_alamat.getText(),
                    TextField_id.getText());
            JOptionPane.showMessageDialog(rootPane, "Data berhasil dirubah");
            //pet.UpdatePetugas(TextField_password.getText(), TextField_nama.getText(), TextField_username.getText(), gender, ComboBox_hakakses.getSelectedItem().toString(), TextArea_alamat.getText(), TextField_id.getText());
            //JOptionPane.showMessageDialog(rootPane, "Data berhasil dirubah");
            jTable_petugas.setModel(pet.viewData());
            kosong();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "data gagaldirubah");
            Logger.getLogger(Petugas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Button_UpdateActionPerformed

    private void Button_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DeleteActionPerformed

        String gender = null;
        String ObjButtons[] = {"Yes", "No"};
        int PromptResult = JOptionPane.showOptionDialog(null, "yakin Mau Hapus ?", "Massage", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, ObjButtons, ObjButtons[1]);
        if (PromptResult == 0) {

            try {
                pet.hapus(TextField_id.getText());
                JOptionPane.showMessageDialog(rootPane, "Data berhasil dihapus");
                jTable_petugas.setModel(pet.viewData());
                kosong();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "data gagal dihapus");
                Logger.getLogger(Petugas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Button_DeleteActionPerformed

    private void jTable_petugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_petugasMouseClicked
        // TODO add your handling code here:
        Button_Create.setVisible(false);
        Button_Delete.setVisible(true);
        Button_Update.setVisible(true);
        int kolom = 0;
        kolom = jTable_petugas.getSelectedRow();
        TextField_id.setText(jTable_petugas.getValueAt(kolom, 0).toString());
        TextField_password.setText(jTable_petugas.getValueAt(kolom, 4).toString());
        TextField_nama.setText(jTable_petugas.getValueAt(kolom, 1).toString());
        TextField_username.setText(jTable_petugas.getValueAt(kolom, 3).toString());
        if (jTable_petugas.getValueAt(kolom, 2).toString().equals("laki-laki")) {
            RadioButton_l.setSelected(true);
        } else {
            RadioButton_p.setSelected(true);
        }
        ComboBox_hakakses.setSelectedItem(jTable_petugas.getValueAt(kolom, 5).toString());
        TextArea_alamat.setText(jTable_petugas.getValueAt(kolom, 6).toString());
        TextField_id.setEnabled(false);
    }//GEN-LAST:event_jTable_petugasMouseClicked

    private void Button_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_newActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_Button_newActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose(); //kode jbutton2 / panggil form lain
        new Menu_Utama().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Petugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Create;
    private javax.swing.JButton Button_Delete;
    private javax.swing.JButton Button_Update;
    private javax.swing.JButton Button_new;
    private javax.swing.JComboBox<String> ComboBox_hakakses;
    private javax.swing.JRadioButton RadioButton_l;
    private javax.swing.JRadioButton RadioButton_p;
    private javax.swing.JTextArea TextArea_alamat;
    private javax.swing.JTextField TextField_id;
    private javax.swing.JTextField TextField_nama;
    private javax.swing.JTextField TextField_password;
    private javax.swing.JTextField TextField_username;
    private javax.swing.JLabel alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel hak;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_petugas;
    private javax.swing.JLabel jenis;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel password;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
