
package pac_form;

import config.Koneksi;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

public class Serch_bpjs extends javax.swing.JFrame {

    Koneksi con = new Koneksi();
    //public Gaji Ga = null;
    public Bpjs Bp = null;
    
    
    
    public DefaultTableModel viewDataserch(){
        DefaultTableModel petugastable = new DefaultTableModel();     
    petugastable.addColumn("NAMA");
    petugastable.addColumn("ID PEGAWAI");
    petugastable.addColumn("NIP");
    petugastable.addColumn("KTP");
    petugastable.addColumn("ID BPJS KESEHATAN");
    petugastable.addColumn("NO BPJS KESEHATAN");
    petugastable.addColumn("FASKES BPJS KESEHATAN");
    petugastable.addColumn("NOMINAL BPJS KESEHATAN");
    petugastable.addColumn("ID BPJS KETENAGAKERJAAN");
    petugastable.addColumn("NO BPJS KETENAGAKERJAAN");
    petugastable.addColumn("NOMINAL");
    
    
        
     try{          
           String sql ="SELECT p.nama,p.id_tpegawai, p.nip, p.no_ktp, bs.id_tbpjs_kesehatan, bs.nomor_bpjs, bs.faskes, bs.nominal, bk.id_tbpjs_tenagakerja, bk.nomor_bpjs, bk.nominal \n"
                    + "FROM pegawai p \n" 
                    + "JOIN bpjs_kesehatan bs ON bs.id_tpegawai = p.id_tpegawai \n"
                    + "JOIN bpjs_ketenagakerjaan bk ON bk.id_tpegawai = p.id_tpegawai \n"
                    + "WHERE bs.nominal = 0 AND bk.nominal = 0";
//                   "SELECT p.nama, p.nip, p.no_ktp, bs.id_tbpjs_kesehatan, bs.nomor_bpjs, bs.faskes, bs.nominal, bk.id_tbpjs_tenagakerja, bk.nomor_bpjs, bk.nominal \n"
//                    + "FROM pegawai p \n"
//                    + "JOIN bpjs_kesehatan bs ON bs.id_tpegawai = p.id_tpegawai \n"
//                    + "JOIN bpjs_ketenagakerjaan bk ON bk.id_tpegawai = p.id_tpegawai";
                   //"select * from pegawai";
           Statement stmt = con.connect().prepareStatement(sql);
           ResultSet res = stmt.executeQuery(sql);
           // Mengisi pegawaiTable dengan perulangan hasil dari Query
	    while (res.next()) {
                petugastable.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6),
                    res.getString(7),
                    res.getString(8),
                    res.getString(9),
                    res.getString(10),
                    res.getString(11),}
//		res.getString(1),
//		res.getString(2),
//                res.getString(10),
//                res.getString(4)}
	      );
            }
        } catch (Exception e) {
        }
     return petugastable;
    }
    
    public Serch_bpjs() {
        initComponents();
        Table_serch_bpjs.setModel(viewDataserch());
        viewDataserch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextField_serch_bpjs = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_serch_bpjs = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Table_serch_bpjs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_serch_bpjs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_serch_bpjsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_serch_bpjs);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\RIFQI\\Pictures\\close png 20.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextField_serch_bpjs, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextField_serch_bpjs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Table_serch_bpjsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_serch_bpjsMouseClicked
        // TODO add your handling code here:
        int tabelSerchbpjs = Table_serch_bpjs.getSelectedRow();
        Bp.namaserchbpjs = Table_serch_bpjs.getValueAt(tabelSerchbpjs, 0).toString();
        Bp.idpegwaiserchbpjs = Table_serch_bpjs.getValueAt(tabelSerchbpjs, 1).toString();  
        Bp.no_ktpserchbpjs = Table_serch_bpjs.getValueAt(tabelSerchbpjs, 3).toString();
        Bp.id_bpjskesehatan = Table_serch_bpjs.getValueAt(tabelSerchbpjs, 4).toString();
        Bp.no_bpjskesehatan = Table_serch_bpjs.getValueAt(tabelSerchbpjs, 5).toString();
        Bp.faskes_kesehatan = Table_serch_bpjs.getValueAt(tabelSerchbpjs, 6).toString();
        Bp.nominal_kesehatan = Table_serch_bpjs.getValueAt(tabelSerchbpjs, 7).toString();
        Bp.id_bpjsketenagakerjaan = Table_serch_bpjs.getValueAt(tabelSerchbpjs, 8).toString();
        Bp.no_bpjsketenagakerjaan = Table_serch_bpjs.getValueAt(tabelSerchbpjs, 9).toString();
        Bp.nominal_ketenagakerjaan = Table_serch_bpjs.getValueAt(tabelSerchbpjs, 10).toString();
        Bp.itemTerpilih();
        this.dispose();
        
    }//GEN-LAST:event_Table_serch_bpjsMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Serch_bpjs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Serch_bpjs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Serch_bpjs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Serch_bpjs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Serch_bpjs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_serch_bpjs;
    private javax.swing.JTextField TextField_serch_bpjs;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
